### ISSUE TITLE
Upload features broken

### ISSUE THREAD

**Issue by makim0n** [laxa/SharpSecretsdump#1]
Upload feature from evil winrm seems to be broken :  
This evil-winrm fork runs on a system with official evil-winrm gems installed.

Initial evil winrm command : `./evil-winrm.rb -i 10.0.0.1-u administator -p 'P@ssw0rd' -s "../ps1/" -e "../exe/"`

```bash
C:\Windows\Temp$ upload
Error: undefined local variable or method `pwd' for #<EvilWinRM:0x000056179d55bb98>
Did you mean?  pid: ["./evil-winrm.rb:668:in `do_command'", "./evil-winrm.rb:633:in `block in main'", "/var/lib/gems/2.7.0/gems/winrm-2.3.6/lib/winrm/connection.rb:42:in `shell'", "./evil-winrm.rb:546:in `main'", "./evil-winrm.rb:1029:in `<main>'"]

Error: Upload failed. Check filenames or paths

C:\Windows\Temp$ upload /home/maki/Documents/tools/exe/sharp.exe .
Error: undefined local variable or method `pwd' for #<EvilWinRM:0x000056179d55bb98>
Did you mean?  pid: ["./evil-winrm.rb:668:in `do_command'", "./evil-winrm.rb:633:in `block in main'", "/var/lib/gems/2.7.0/gems/winrm-2.3.6/lib/winrm/connection.rb:42:in `shell'", "./evil-winrm.rb:546:in `main'", "./evil-winrm.rb:1029:in `<main>'"]

Error: Upload failed. Check filenames or paths

C:\Windows\Temp$ upload /home/maki/Documents/tools/exe/sharp.exe
Error: undefined local variable or method `pwd' for #<EvilWinRM:0x000056179d55bb98>
Did you mean?  pid: ["./evil-winrm.rb:668:in `do_command'", "./evil-winrm.rb:633:in `block in main'", "/var/lib/gems/2.7.0/gems/winrm-2.3.6/lib/winrm/connection.rb:42:in `shell'", "./evil-winrm.rb:546:in `main'", "./evil-winrm.rb:1029:in `<main>'"]

Error: Upload failed. Check filenames or paths
```

The official evil-winrm project works :  

```bash
Evil-WinRM shell v3.4
Info: Establishing connection to remote endpoint

*Evil-WinRM* PS C:\Users\loginsec\Documents> cd C:\Windows\Temp
*Evil-WinRM* PS C:\Windows\Temp> upload /home/maki/Documents/tools/exe/sharp.exe
Info: Uploading /home/maki/Documents/tools/exe/sharp.exe to C:\Windows\Temp\sharp.exe

Data: 47784 bytes of 47784 bytes copied
Info: Upload successful!

*Evil-WinRM* PS C:\Windows\Temp> dir

    Directory: C:\Windows\Temp

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       12/21/2022  12:21 PM          35840 sharp.exe
```

**Comment by makim0n** [comment]
Wrong git :)
